FROM nvcr.io/nvidia/tensorrt:24.06-py3

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH=/workspace/scindo-models/src

WORKDIR /workspace/scindo-models

RUN pip install --no-cache-dir --upgrade pip

COPY pyproject.toml ./
COPY src/ ./src/
COPY models/ ./models/

RUN pip install --no-cache-dir -e ".[onnxruntime-trt]"

CMD ["python"]
